spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_lesson_contact
    username: root
    password: 231486
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
